### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mechanicalDX** [Rinnegatamante/DaedalusX64-vitaGL#199] opened 2020-08-08 19:38 UTC
Describe the bug
Daedalus loads up to the gamelist download screen but crashes before displaying roms and reports a crash dump with error "Undefined instruction exception"

To Reproduce
Unsure of the cause

![IMG_20200808_120945.jpg](https://user-images.githubusercontent.com/46545671/89717874-6a863900-d96f-11ea-8b2d-128c4e0c43d1.jpg)

![IMG_20200808_121004.jpg](https://user-images.githubusercontent.com/46545671/89717880-74a83780-d96f-11ea-9ca1-7d5fd07c9d7e.jpg)

 - Device: Vita (2000)
 - FW:3.60 Ensō
 - Daedalus Version 0.4

**Comment by Sarkie** [comment] 2020-08-08 21:03
Update to latest nightly

**Comment by Rinnegatamante** [comment] 2020-08-09 09:34
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL/issues/187

**Closed by Rinnegatamante** 2020-08-09 09:34 UTC
